#!/bin/bash

echo "Diretórios"

mkdir /publico
mkdir /adm
mkdir /ven
mdkir /sec

echo "Grupos"

groupadd GRP_ADM
groupadd GRP_VEN
groupadd GRP_SEC

echo "Usuários"

useradd carlos -m -c "Carlos" -s /bin/bash -p $(openssl passwd 123)
passwd carlos -e

useradd maria -m -c "Maria" -s /bin/bash -p $(openssl passwd 123)
passwd maria -e

useradd joao -m -c "João" -s /bin/bash -p $(openssl passwd 123)
passwd joao -e

useradd debora -m -c "Debora" -s /bin/bash -p $(openssl passwd 123)
passwd debora -e

useradd sebastiana -m -c "Sebastiana" -s /bin/bash -p $(openssl passwd 123)
passwd sebastiana -e

useradd roberto -m -c "Roberto" -s /bin/bash -p $(openssl passwd 123)
passwd roberto -e

useradd josefina -m -c "Josefina" -s /bin/bash -p $(openssl passwd 123)
passwd josefina -e

useradd amanda -m -c "Amanda" -s /bin/bash -p $(openssl passwd 123)
passwd amanda -e

useradd rogerio -m -c "Rogério" -s /bin/bash -p $(openssl passwd 123)
passwd rogerio -e

echo "Usuários nos grupos"

usermod -G GRP_ADM carlos; usermod -G GRP_ADM maria; usermod -G GRP_ADM joao
usermod -G GRP_VEN debora; usermod -G GRP_VEN sebastiana; usermod -G GRP_VEN roberto
usermod -G GRP_SEC josefina; usermod -G GRP_SEC amanda; usermod -G GRP_SEC rogerio

echo "permissões de diretórios"

chown root:GRP_ADM /adm/
chown root:GRP_VEN /ven/
chown root:GRP_SEC /sec/

chmod 770 /adm/
chmod 770 /ven/
chmod 770 /sec/
chmod 777 /publico/

echo "Criação de grupos,usuários e diretórios finalizado!!!"
